# サイクル定義テンプレート

cycle_id: "C-{{NNN}}"
trigger: "{{new_product / feature_addition / bug_fix / tech_change}}"
title: "{{変更のタイトル}}"
design_ref: "docs/apd/design/product-design.yaml"
started_at: "YYYY-MM-DDTHH:MM:SSZ"
completed_at: null # 完了時に記入

# フェーズ通過記録
phases:
  design: # new_product のみ
    status: "{{skipped / completed}}"
    checkpoint_at: null
  spec:
    status: "{{skipped / completed}}"
    checkpoint_at: null
  contract:
    status: "{{skipped / completed}}"
    checkpoint_at: null
  execute:
    status: "{{pending / in_progress / completed}}"
    checkpoint_at: null

# Spec変更
spec_changes:
  - type: "{{new_spec / amendment}}"
    id: "{{SPEC_ID}}" # new_spec の場合
    target: "{{既存SPEC_ID}}" # amendment の場合
    amendment_id: "A-{{NNN}}" # amendment の場合
    context: "{{コンテキスト名}}"

# Contract変更
contract_changes:
  - type: "{{new / amendment}}"
    amendment_id: "C-{{NNN}}" # amendment の場合
    change: "{{変更概要}}"

# 判断記録（サイクル中に追加される）
decisions: []
  # - D-012: "判断の要約"
